Repository fga-eps-mds/2023-1-CAPJu-Doc, pull requests merged in 2023-05, with the labels that each got.

#48 Criar documento de backlog do produto #42
  docs/backlog_do_produto.md
  mkdocs.yml
Labels: documentation

#54 Cria plano de gerenciamento de riscos
  docs/plano_de_gerenciamento_de_riscos.md
  mkdocs.yml
Labels: documentation

#118 (#60) - Adiciona doc de planejamento
  docs/planejamento.md
  mkdocs.yml
Labels: documentation, DOCS

#126 Modificar a página inicial da documentação
  docs/index.md
Labels: documentation

#131 (#127) - Documentar as ferramentas utilizadas pela equipe
  docs/ferramentas_utilizadas_pela_equipe.md
  mkdocs.yml
Labels: documentation, DOCS

#147 Configurando ambiente virtualizado para Documentação
  Dockerfile
  docker-compose.yml
Labels: devops

#129 (fga-eps-mds/2023-1-CAPJu-Doc#15) Atualiza o padrão de commit
  docs/politica_de_contribuicao.md
Labels: documentation

#149 (#148) - Atualiza datas do documento
  docs/planejamento.md
Labels: documentation

#119 (fga-eps-mds/2023-1-CAPJu-Doc#109) - Substitui tabela de treinamento…
  docs/Controle/cronograma_de_dojo.md
  docs/Relatórios/semana1.md
  docs/Relatórios/semana2.md
Labels: documentation

#115 (#37) - Documento de arquitetura
  docs/DAS/documento_de_arquitetura.md
  docs/assets/DER.png
  docs/assets/DLD.png
  docs/assets/diagrama_de_pacotes.drawio
  mkdocs.yml
Labels: documentation

#108 (#61) - Implementa documento de comunicação.
  docs/comunicacao.md
  mkdocs.yml
Labels: documentation

#153 [WIP] Adiciona atas da reunião
  docs/Relatórios/relatorios_do_projeto.md
  docs/Relatórios/semana2.md
  docs/Relatórios/semana3.md
  docs/Relatórios/semana4.md
  docs/Relatórios/semana5.md
  docs/Relatórios/semana6.md
  docs/Relatórios/sprint1.md
  docs/Relatórios/sprint2.md
  docs/planejamento.md
Labels: documentation
